#pragma once

#include "pebble.h"

#define NUM_CLOCK_TICKS 11

#define TANG_30_X1000 0.578 * 1000.0
#define TANG_60_X1000 1.732 * 1000.0

#define PBL_DISPLAY_WIDTH_HALF PBL_DISPLAY_WIDTH / 2
#define PBL_DISPLAY_HEIGHT_HALF PBL_DISPLAY_HEIGHT / 2

#define CIRCLE_RADIUS 2
#define CIRCLE_CORNER_OFFSET 2

#define CIRCLE_ONE_POS_X (PBL_DISPLAY_WIDTH_HALF + ((TANG_30_X1000*(PBL_DISPLAY_HEIGHT_HALF)/1000)))
#define CIRCLE_ONE_POS_Y CIRCLE_RADIUS + CIRCLE_CORNER_OFFSET

#define CIRCLE_TWO_POS_X PBL_DISPLAY_WIDTH - (CIRCLE_RADIUS + CIRCLE_CORNER_OFFSET)
#define CIRCLE_TWO_POS_Y PBL_DISPLAY_HEIGHT_HALF - (TANG_30_X1000*(PBL_DISPLAY_WIDTH_HALF)/1000)

#define CIRCLE_THREE_POS_X PBL_DISPLAY_WIDTH - (CIRCLE_RADIUS + CIRCLE_CORNER_OFFSET)
#define CIRCLE_THREE_POS_Y PBL_DISPLAY_HEIGHT_HALF

#define CIRCLE_FOUR_POS_X PBL_DISPLAY_WIDTH - (CIRCLE_RADIUS + CIRCLE_CORNER_OFFSET)
#define CIRCLE_FOUR_POS_Y PBL_DISPLAY_HEIGHT_HALF + (TANG_30_X1000*(PBL_DISPLAY_WIDTH_HALF)/1000)

#define CIRCLE_FIVE_POS_X (PBL_DISPLAY_WIDTH_HALF + ((TANG_30_X1000*(PBL_DISPLAY_HEIGHT_HALF)/1000)))
#define CIRCLE_FIVE_POS_Y PBL_DISPLAY_HEIGHT - (CIRCLE_RADIUS + CIRCLE_CORNER_OFFSET)

#define CIRCLE_SIX_POS_X PBL_DISPLAY_WIDTH_HALF - CIRCLE_RADIUS
#define CIRCLE_SIX_POS_Y PBL_DISPLAY_HEIGHT - (CIRCLE_RADIUS + CIRCLE_CORNER_OFFSET)

#define CIRCLE_SEVEN_POS_X (PBL_DISPLAY_WIDTH_HALF - ((TANG_30_X1000*(PBL_DISPLAY_HEIGHT_HALF)/1000)))
#define CIRCLE_SEVEN_POS_Y PBL_DISPLAY_HEIGHT - (CIRCLE_RADIUS + CIRCLE_CORNER_OFFSET)

#define CIRCLE_EIGHT_POS_X CIRCLE_RADIUS + CIRCLE_CORNER_OFFSET
#define CIRCLE_EIGHT_POS_Y PBL_DISPLAY_HEIGHT_HALF + (TANG_30_X1000*(PBL_DISPLAY_WIDTH_HALF)/1000)

#define CIRCLE_NINE_POS_X CIRCLE_RADIUS + CIRCLE_CORNER_OFFSET
#define CIRCLE_NINE_POS_Y PBL_DISPLAY_HEIGHT_HALF

#define CIRCLE_TEN_POS_X CIRCLE_RADIUS + CIRCLE_CORNER_OFFSET
#define CIRCLE_TEN_POS_Y PBL_DISPLAY_HEIGHT_HALF - (TANG_30_X1000*(PBL_DISPLAY_WIDTH_HALF)/1000)

#define CIRCLE_ELEVEN_POS_X (PBL_DISPLAY_WIDTH_HALF - ((TANG_30_X1000*(PBL_DISPLAY_HEIGHT_HALF)/1000)))
#define CIRCLE_ELEVEN_POS_Y CIRCLE_RADIUS + CIRCLE_CORNER_OFFSET

#define CIRCLE_TWELVE_POS_X PBL_DISPLAY_WIDTH_HALF
#define CIRCLE_TWELVE_POS_Y CIRCLE_RADIUS + CIRCLE_CORNER_OFFSET
